"""Unit tests for zpl_toolkit core modules."""
import json
import os
import tempfile
from datetime import datetime

import pytest

from zpl_toolkit.types import (
    ConnectionConfig,
    ZPLExecutionResult,
    ZPLError,
    ZPLParseResult,
    MacroInfo,
    RegressionTestResult,
    GenerationTemplate,
)
from zpl_toolkit.parser import ZPLParser
from zpl_toolkit.generator import ZPLGenerator
from zpl_toolkit.manager import ZPLManager
from zpl_toolkit.regression import RegressionRunner


# ═══════════════════════════════════════════════════════════════
# Types
# ═══════════════════════════════════════════════════════════════

class TestTypes:
    def test_connection_config_defaults(self):
        c = ConnectionConfig()
        assert c.opticstudio_path is None
        assert c.headless is True
        assert c.timeout == 60
        assert "auto" in str(c)

    def test_zpl_execution_result_str(self):
        r = ZPLExecutionResult(0, "hello", "", 1.5, "test.zpl")
        assert "OK" in str(r)
        r2 = ZPLExecutionResult(1, "", "err", 0.1, "fail.zpl")
        assert "FAIL" in str(r2)

    def test_zpl_error_str(self):
        e = ZPLError(42, "E_UNDEFINED", "Undefined FOO", "ERROR")
        s = str(e)
        assert "L42" in s
        assert "FOO" in s

    def test_macro_info_defaults(self):
        m = MacroInfo(
            path="/tmp/t.zpl",
            name="t.zpl",
            size=100,
            last_modified=datetime.now(),
        )
        assert m.category == "general"
        assert m.line_count == 0

    def test_regression_test_result_str(self):
        r = RegressionTestResult("t.zpl", True, "a", "a", "")
        assert "PASS" in str(r)
        r2 = RegressionTestResult("f.zpl", False, "a", "b", "diff here")
        assert "FAIL" in str(r2)

    def test_generation_template_str(self):
        t = GenerationTemplate("test", "desc", {"x": None}, "body")
        assert "test" in str(t)


# ═══════════════════════════════════════════════════════════════
# Parser
# ═══════════════════════════════════════════════════════════════

class TestParser:
    def test_parse_error_line(self):
        parser = ZPLParser()
        result = ZPLExecutionResult(
            1, "", "Error at line 42: Undefined variable FOO", 0.1, "t.zpl"
        )
        parsed = parser.parse(result)
        assert len(parsed.errors) == 1
        assert parsed.errors[0].line_number == 42
        assert "FOO" in parsed.errors[0].message
        assert parsed.errors[0].severity == "ERROR"

    def test_parse_warning_line(self):
        parser = ZPLParser()
        result = ZPLExecutionResult(
            0, "", "Warning: Deprecated function", 0.1, "t.zpl"
        )
        parsed = parser.parse(result)
        assert len(parsed.errors) == 1
        assert parsed.errors[0].severity == "WARNING"

    def test_parse_empty_output(self):
        parser = ZPLParser()
        result = ZPLExecutionResult(0, "", "", 0.1, "t.zpl")
        parsed = parser.parse(result)
        assert len(parsed.errors) == 0
        assert not parsed.has_errors

    def test_parse_unknown_error(self):
        parser = ZPLParser()
        result = ZPLExecutionResult(
            1, "", "Something failed unexpectedly", 0.1, "t.zpl"
        )
        parsed = parser.parse(result)
        assert len(parsed.errors) == 1
        assert parsed.errors[0].error_code == "E_UNKNOWN"

    def test_extract_data_key_value(self):
        parser = ZPLParser()
        result = ZPLExecutionResult(
            0, "Field=0.5\nDistortion=2.34", "", 0.1, "t.zpl"
        )
        parsed = parser.parse(result)
        assert parsed.data == {"Field": 0.5, "Distortion": 2.34}

    def test_parse_multiline_error(self):
        parser = ZPLParser()
        stderr = "Error at line 10: Syntax error\nError at line 20: Type mismatch\n"
        result = ZPLExecutionResult(1, "", stderr, 0.1, "t.zpl")
        parsed = parser.parse(result)
        assert len(parsed.errors) == 2


# ═══════════════════════════════════════════════════════════════
# Generator
# ═══════════════════════════════════════════════════════════════

class TestGenerator:
    def test_builtin_templates_loaded(self):
        gen = ZPLGenerator()
        names = [t.name for t in gen.list_templates()]
        assert "tilt-analysis" in names
        assert "distortion" in names
        assert "mtf-analysis" in names

    def test_generate_tilt_analysis(self):
        gen = ZPLGenerator()
        code = gen.generate("tilt-analysis", {"lens_file": "test.zmx", "field_count": 5})
        assert "test.zmx" in code
        assert "FOR i, 1, 5, 1" in code
        assert "NEXT" in code
        assert "Auto-generated by zpl_toolkit" in code

    def test_generate_missing_required_param(self):
        gen = ZPLGenerator()
        with pytest.raises(ValueError, match="lens_file"):
            gen.generate("tilt-analysis", {})

    def test_generate_unknown_template(self):
        gen = ZPLGenerator()
        with pytest.raises(KeyError, match="nonexistent"):
            gen.generate("nonexistent", {})

    def test_save_and_file_exists(self):
        gen = ZPLGenerator()
        with tempfile.NamedTemporaryFile(suffix=".zpl", delete=False) as f:
            path = f.name
        try:
            gen.save("tilt-analysis", {"lens_file": "t.zmx"}, path, force=True)
            with open(path, encoding="utf-8") as f:
                content = f.read()
            assert "t.zmx" in content
        finally:
            os.unlink(path)

    def test_save_file_exists_no_force(self):
        gen = ZPLGenerator()
        with tempfile.NamedTemporaryFile(suffix=".zpl", delete=False) as f:
            path = f.name
        try:
            gen.save("tilt-analysis", {"lens_file": "t.zmx"}, path, force=True)
            with pytest.raises(FileExistsError):
                gen.save("tilt-analysis", {"lens_file": "t.zmx"}, path, force=False)
        finally:
            os.unlink(path)

    def test_default_params_applied(self):
        gen = ZPLGenerator()
        code = gen.generate("distortion", {"lens_file": "test.zmx"})
        assert "test.zmx" in code
        # Default param (reference_wavelength=1) should be substituted
        assert "$" not in code or "PRIMARY $reference_wavelength" not in code


# ═══════════════════════════════════════════════════════════════
# Manager
# ═══════════════════════════════════════════════════════════════

class TestManager:
    def _make_zpl_dir(self, files: dict):
        """Create a temporary directory with .ZPL files from a dict of {name: content}."""
        tmpdir = tempfile.mkdtemp()
        for name, content in files.items():
            path = os.path.join(tmpdir, name)
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
        return tmpdir

    def test_discover_single(self):
        files = {"test.ZPL": "! test macro\nPRINT 'hello'"}
        d = self._make_zpl_dir(files)
        try:
            manager = ZPLManager()
            macros = manager.discover(d)
            assert len(macros) == 1
            assert macros[0].name == "test.ZPL"
            assert macros[0].line_count == 2
            assert macros[0].size > 0
        finally:
            import shutil
            shutil.rmtree(d, ignore_errors=True)

    def test_discover_multiple(self):
        files = {f"macro_{i}.ZPL": f"! macro {i}" for i in range(5)}
        d = self._make_zpl_dir(files)
        try:
            manager = ZPLManager()
            macros = manager.discover(d, recursive=False)
            assert len(macros) == 5
        finally:
            import shutil
            shutil.rmtree(d, ignore_errors=True)

    def test_discover_nonexistent_dir(self):
        manager = ZPLManager()
        with pytest.raises(FileNotFoundError):
            manager.discover("/nonexistent/path/xyz")

    def test_categorize(self):
        files = {
            "tilt_test.ZPL": "! tilt analysis",
            "distortion_test.ZPL": "! distortion calc",
            "unknown_test.ZPL": "! something",
        }
        d = self._make_zpl_dir(files)
        try:
            manager = ZPLManager()
            macros = manager.discover(d)
            cats = manager.categorize(macros)
            assert "tilt_analysis" in cats
            assert "distortion" in cats
            assert "general" in cats
        finally:
            import shutil
            shutil.rmtree(d, ignore_errors=True)

    def test_search(self):
        files = {
            "HUD_test.ZPL": "! hud analysis",
            "other.ZPL": "! something else",
        }
        d = self._make_zpl_dir(files)
        try:
            manager = ZPLManager()
            results = manager.search(d, "HUD")
            assert len(results) == 1
            assert "HUD" in results[0].name
        finally:
            import shutil
            shutil.rmtree(d, ignore_errors=True)


# ═══════════════════════════════════════════════════════════════
# Regression
# ═══════════════════════════════════════════════════════════════

class TestRegression:
    def test_compare_outputs_identical(self):
        from unittest.mock import MagicMock
        runner = RegressionRunner(MagicMock(), MagicMock())
        assert runner.compare_outputs("hello", "hello") is True
        assert runner.compare_outputs("", "") is True

    def test_compare_outputs_different(self):
        from unittest.mock import MagicMock
        runner = RegressionRunner(MagicMock(), MagicMock())
        assert runner.compare_outputs("hello", "world") is False

    def test_compare_outputs_one_empty(self):
        from unittest.mock import MagicMock
        runner = RegressionRunner(MagicMock(), MagicMock())
        assert runner.compare_outputs("", "hello") is False

    def test_baseline_path_generation(self):
        from unittest.mock import MagicMock
        runner = RegressionRunner(MagicMock(), MagicMock())
        path = runner._baseline_path("/tmp/test.ZPL", ".baselines")
        assert "test.baseline.json" in path
        assert ".baselines" in path
