"""ZPL code generator with built-in templates."""

import logging
import os
from string import Template
from typing import Optional

from zpl_toolkit.types import GenerationTemplate

logger = logging.getLogger(__name__)


# ── Built-in templates ─────────────────────────────────────────

_BUILTIN_TEMPLATES = {
    "tilt-analysis": GenerationTemplate(
        name="tilt-analysis",
        description="Image tilt analysis macro",
        parameters={
            "lens_file": None,
            "field_count": 19,
            "save_report": True,
            "config": 1,
        },
        template_body='''! Tilt Analysis – Auto-generated by zpl_toolkit
! Lens: $lens_file | Fields: $field_count | Config: $config

! Load lens
OPEN "$lens_file"

! Set up analysis
SETCONFIG $config
NSTR 0, $field_count, 0, 0, 0, 0

! Run tilt calculation loop
DECLARE i, DOUBLE
DECLARE tilt_x, DOUBLE
DECLARE tilt_y, DOUBLE

FOR i, 1, $field_count, 1
    ! Get field data
    FLDX = FLDX(i)
    FLDY = FLDY(i)
    
    ! Calculate tilt from ray angles
    RAYTRACE 0, 0, 0, 0
    tilt_x = ATAN(OPDC(i))
    tilt_y = ATAN(OPDC(i + 10))
    
    PRINT "Field ", i
    PRINT "Tilt_X=", tilt_x
    PRINT "Tilt_Y=", tilt_y
NEXT

#if $save_report:
    PRINT "Report complete"
#endif
''',
    ),
    "distortion": GenerationTemplate(
        name="distortion",
        description="Distortion calculation macro",
        parameters={
            "lens_file": None,
            "config": 1,
            "reference_wavelength": 1,
        },
        template_body='''! Distortion Analysis – Auto-generated by zpl_toolkit
! Lens: $lens_file | Wavelength: $reference_wavelength

OPEN "$lens_file"
SETCONFIG $config

! Set reference wavelength
PRIMARY $reference_wavelength

! Calculate distortion
GETSYSDATA 201  ! Max field
DECLARE max_field, DOUBLE
max_field = VEC1(201)

DECLARE field, DOUBLE
DECLARE distortion, DOUBLE

FOR field, 0, 1, 0.1
    FLDX = field
    
    ! Ray trace chief ray
    RAYTRACE 0, 0, 0, 0, 1
    
    ! Calculate distortion
    distortion = (REAY(0) - field * EFLX()) / (field * EFLX()) * 100
    PRINT "Field=", field
    PRINT "Distortion_percent=", distortion
NEXT

PRINT "Analysis complete"
''',
    ),
    "mtf-analysis": GenerationTemplate(
        name="mtf-analysis",
        description="MTF analysis wrapper macro",
        parameters={
            "lens_file": None,
            "config": 1,
            "frequency": 30,
            "fields": "0, 0.5, 0.7, 1.0",
        },
        template_body='''! MTF Analysis – Auto-generated by zpl_toolkit
! Lens: $lens_file | Freq: $frequency lp/mm | Config: $config

OPEN "$lens_file"
SETCONFIG $config

! Set MTF frequency
MTFA $frequency

! Run MTF for each specified field
PRINT "MTF Analysis at $frequency lp/mm"
PRINT "Field, Tangential, Sagittal"

DECLARE field_idx, INTEGER
DECLARE field_val, DOUBLE
DECLARE mtf_t, DOUBLE
DECLARE mtf_s, DOUBLE

! Sample across fields
FOR field_idx, 0, 3, 1
    IF field_idx == 0
        field_val = 0
    ELSEIF field_idx == 1
        field_val = 0.5
    ELSEIF field_idx == 2
        field_val = 0.7
    ELSE
        field_val = 1.0
    ENDIF
    
    FLDX = field_val
    FLDY = 0
    
    ! Get MTF
    GETMTF 0, $frequency, 0, 0
    mtf_t = OPDC(1)
    mtf_s = OPDC(2)
    
    PRINT field_val, ",", mtf_t, ",", mtf_s
NEXT

PRINT "MTF analysis complete"
''',
    ),
}


# ── Generator class ────────────────────────────────────────────


class ZPLGenerator:
    """Generates ZPL macros from parameterized templates."""

    def __init__(self):
        self._templates: dict[str, GenerationTemplate] = {}
        self.load_builtin_templates()

    def load_builtin_templates(self):
        """Load built-in templates into the generator."""
        for name, tmpl in _BUILTIN_TEMPLATES.items():
            self.register_template(tmpl)
        logger.debug("Loaded %d built-in templates", len(_BUILTIN_TEMPLATES))

    def register_template(self, template: GenerationTemplate):
        """Register a generation template."""
        self._templates[template.name] = template
        logger.debug("Registered template: %s", template.name)

    def list_templates(self) -> list[GenerationTemplate]:
        """Return all registered templates."""
        return list(self._templates.values())

    def get_template(self, name: str) -> GenerationTemplate:
        """Get a template by name. Raises KeyError if not found."""
        if name not in self._templates:
            available = ", ".join(self._templates.keys())
            raise KeyError(
                f"Template '{name}' not found. Available: {available}"
            )
        return self._templates[name]

    def generate(self, template_name: str, params: dict) -> str:
        """Generate ZPL code from a template.

        Args:
            template_name: Name of the registered template.
            params: Dict of parameter values. Missing params use defaults.

        Returns:
            Generated ZPL code as a string.

        Raises:
            KeyError: Template not found.
            ValueError: Required parameter missing (no default).
        """
        tmpl = self.get_template(template_name)

        # Merge params with defaults
        merged: dict[str, str] = {}
        for key, default in tmpl.parameters.items():
            if key in params and params[key] is not None:
                merged[key] = str(params[key])
            elif default is not None:
                merged[key] = str(default)
            else:
                raise ValueError(
                    f"Required parameter '{key}' not provided for template '{template_name}'. "
                    f"Required params: {list(tmpl.parameters.keys())}"
                )

        # Simple {key} substitution
        result = tmpl.template_body
        for key, value in merged.items():
            result = result.replace("$" + key, str(value))

        # Handle #if blocks
        result = self._process_conditionals(result, merged)

        return result

    def _process_conditionals(self, code: str, params: dict[str, str]) -> str:
        """Process simple #if param: ... #endif blocks."""
        lines = code.splitlines()
        output: list[str] = []
        skip = False

        for line in lines:
            stripped = line.strip()
            if stripped.startswith("#if "):
                var_name = stripped[4:].split(":")[0].strip().lstrip("$")
                value = params.get(var_name, "0")
                skip = value.lower() not in ("true", "1", "yes")
                continue
            elif stripped.startswith("#endif"):
                skip = False
                continue
            elif not skip:
                output.append(line)

        return "\n".join(output)

    def save(
        self,
        template_name: str,
        params: dict,
        output_path: str,
        force: bool = False,
    ) -> str:
        """Generate and save ZPL code to a file.

        Args:
            template_name: Name of the registered template.
            params: Dict of parameter values.
            output_path: Path to save the generated ZPL file.
            force: Overwrite existing file if True.

        Returns:
            Path to the saved file.

        Raises:
            FileExistsError: File exists and force is False.
        """
        if os.path.exists(output_path) and not force:
            raise FileExistsError(
                f"File already exists: {output_path}. Use force=True to overwrite."
            )

        code = self.generate(template_name, params)
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(code)

        logger.info("Generated ZPL saved: %s (%d lines)", output_path, len(code.splitlines()))
        return output_path
